### ISSUE TITLE
In installation download of Microsoft Remote Desktop assistant

### ISSUE THREAD

**Issue by escape0707** [gfwlist/gfwlist#398]
[Tool's download page](https://www.microsoft.com/en-us/download/details.aspx?id=50042)
As titled, in installation download requires breaking the block to finish. Once finished downloading, unblocking is not required again and makes it more difficult to reproduce it.
Global proxy will can fix it but PAC won't.
China Telecom, Jiangsu

**Comment by cicku** [comment]
```
PLATFORM VERSION INFO
	Windows 			: 10.0.14393.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.6.1586.0 built by: NETFXREL2
	clr.dll 			: 4.6.1586.0 built by: NETFXREL2
	dfdll.dll 			: 4.6.1586.0 built by: NETFXREL2
	dfshim.dll 			: 10.0.14393.0 (rs1_release.160715-1616)

SOURCES
	Deployment url			: file:///C:/Users/X/Downloads/rdassistant.application
	Deployment Provider url		: http://download.microsoft.com/download/1/3/2/1322897E-11C1-4E30-9EFC-70C1C2219048/rdassistant.application

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\X\Downloads\rdassistant.application resulted in exception. Following failure messages were detected:
		+ Downloading http://download.microsoft.com/download/1/3/2/1322897E-11C1-4E30-9EFC-70C1C2219048/rdassistant.application did not succeed.
		+ The remote server returned an error: (504) Gateway Timeout.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [2/10/2017 6:33:15 PM] : Activation of C:\Users\X\Downloads\rdassistant.application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [2/10/2017 6:34:16 PM] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
		- Downloading http://download.microsoft.com/download/1/3/2/1322897E-11C1-4E30-9EFC-70C1C2219048/rdassistant.application did not succeed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState, X509Certificate2 clientCertificate)
			at System.Deployment.Application.DownloadManager.DownloadManifestAsRawFile(Uri& sourceUri, String targetPath, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirect(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.FollowDeploymentProviderUri(SubscriptionStore subStore, AssemblyManifest& deployment, Uri& sourceUri, TempFile& tempFile, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Net.WebException
		- The remote server returned an error: (504) Gateway Timeout.
		- Source: System
		- Stack trace:
			at System.Net.HttpWebRequest.GetResponse()
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.
```

**Comment by cicku** [comment]
我看了看这个 app file，貌似里面的链接有 HTTP 形式的。

我自己通过北京电信测试多次均无法下载，然而在我通过 Windows Store 下载 `Microsoft Remote Desktop Preview` 后，这个 app file 便连接成功了，随后重复测试又多次失败。

目前我只能建议您多试几次，或者您通过 Windows Store 下载这个程序（Windows Store 版本会最终替代您给的链接，但是 Windows 7 并没有 Store 可用）：

`https://www.microsoft.com/en-us/store/p/microsoft-remote-desktop-preview`

**Comment by zzhhbyt1** [comment]
If PAC proxy with gfwlist can't solve the problem, just try to use global proxy.
The initial intention to open this issue is to find which new Microsoft or related third-party servers is currently blocked earlier, and prevent further problems while using Windows.
全局socks5代理可以解决问题，采用gfwlist的PAC不能成功解决链接问题。
提出这个issue的本意是提早发现不能访问的服务器并设置到gfwlist中以防止潜在的Windows使用过程中的问题。

**Comment by cicku** [comment]
问题应该是 `download.microsoft.com` 在蓝汛出现504。
